package io.signoz.springboot.database;

import io.signoz.springboot.properties.SigNozDatabaseProperties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.sql.DataSource;
import java.io.PrintWriter;
import java.sql.*;
// java.util.logging.Logger used via FQN in getParentLogger()

/**
 * A {@link DataSource} wrapper that times SQL query execution and logs
 * slow queries at WARN level.
 *
 * <p>When {@code signoz.database.log-all-queries} is enabled, every query
 * is logged at INFO level with its duration. Queries exceeding
 * {@code signoz.database.slow-query-threshold-ms} are always logged at WARN.
 */
public class TracingDataSourceProxy implements DataSource {

    private static final Logger log = LoggerFactory.getLogger("SIGNOZ_DB");

    private final DataSource delegate;
    private final SigNozDatabaseProperties props;

    public TracingDataSourceProxy(DataSource delegate, SigNozDatabaseProperties props) {
        this.delegate = delegate;
        this.props = props;
    }

    @Override
    public Connection getConnection() throws SQLException {
        return new TracingConnectionProxy(delegate.getConnection());
    }

    @Override
    public Connection getConnection(String username, String password) throws SQLException {
        return new TracingConnectionProxy(delegate.getConnection(username, password));
    }

    // --- Delegate methods ---
    @Override public PrintWriter getLogWriter() throws SQLException { return delegate.getLogWriter(); }
    @Override public void setLogWriter(PrintWriter out) throws SQLException { delegate.setLogWriter(out); }
    @Override public void setLoginTimeout(int seconds) throws SQLException { delegate.setLoginTimeout(seconds); }
    @Override public int getLoginTimeout() throws SQLException { return delegate.getLoginTimeout(); }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { return delegate.unwrap(iface); }
    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return delegate.isWrapperFor(iface); }
    @Override public java.util.logging.Logger getParentLogger() throws SQLFeatureNotSupportedException { return delegate.getParentLogger(); }

    /** Returns the original unwrapped DataSource. */
    public DataSource getDelegate() { return delegate; }

    /**
     * Connection wrapper that intercepts {@code prepareStatement} and
     * {@code createStatement} to return timing-aware statement proxies.
     */
    private class TracingConnectionProxy implements Connection {

        private final Connection delegate;

        TracingConnectionProxy(Connection delegate) {
            this.delegate = delegate;
        }

        @Override
        public PreparedStatement prepareStatement(String sql) throws SQLException {
            return new TracingPreparedStatementProxy(delegate.prepareStatement(sql), sql);
        }

        @Override
        public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
            return new TracingPreparedStatementProxy(delegate.prepareStatement(sql, resultSetType, resultSetConcurrency), sql);
        }

        @Override
        public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
            return new TracingPreparedStatementProxy(delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), sql);
        }

        @Override
        public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
            return new TracingPreparedStatementProxy(delegate.prepareStatement(sql, autoGeneratedKeys), sql);
        }

        @Override
        public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
            return new TracingPreparedStatementProxy(delegate.prepareStatement(sql, columnIndexes), sql);
        }

        @Override
        public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
            return new TracingPreparedStatementProxy(delegate.prepareStatement(sql, columnNames), sql);
        }

        // --- All other Connection methods delegate directly ---
        @Override public Statement createStatement() throws SQLException { return delegate.createStatement(); }
        @Override public Statement createStatement(int r, int c) throws SQLException { return delegate.createStatement(r, c); }
        @Override public Statement createStatement(int r, int c, int h) throws SQLException { return delegate.createStatement(r, c, h); }
        @Override public CallableStatement prepareCall(String sql) throws SQLException { return delegate.prepareCall(sql); }
        @Override public CallableStatement prepareCall(String sql, int r, int c) throws SQLException { return delegate.prepareCall(sql, r, c); }
        @Override public CallableStatement prepareCall(String sql, int r, int c, int h) throws SQLException { return delegate.prepareCall(sql, r, c, h); }
        @Override public String nativeSQL(String sql) throws SQLException { return delegate.nativeSQL(sql); }
        @Override public void setAutoCommit(boolean autoCommit) throws SQLException { delegate.setAutoCommit(autoCommit); }
        @Override public boolean getAutoCommit() throws SQLException { return delegate.getAutoCommit(); }
        @Override public void commit() throws SQLException { delegate.commit(); }
        @Override public void rollback() throws SQLException { delegate.rollback(); }
        @Override public void close() throws SQLException { delegate.close(); }
        @Override public boolean isClosed() throws SQLException { return delegate.isClosed(); }
        @Override public DatabaseMetaData getMetaData() throws SQLException { return delegate.getMetaData(); }
        @Override public void setReadOnly(boolean readOnly) throws SQLException { delegate.setReadOnly(readOnly); }
        @Override public boolean isReadOnly() throws SQLException { return delegate.isReadOnly(); }
        @Override public void setCatalog(String catalog) throws SQLException { delegate.setCatalog(catalog); }
        @Override public String getCatalog() throws SQLException { return delegate.getCatalog(); }
        @Override public void setTransactionIsolation(int level) throws SQLException { delegate.setTransactionIsolation(level); }
        @Override public int getTransactionIsolation() throws SQLException { return delegate.getTransactionIsolation(); }
        @Override public SQLWarning getWarnings() throws SQLException { return delegate.getWarnings(); }
        @Override public void clearWarnings() throws SQLException { delegate.clearWarnings(); }
        @Override public java.util.Map<String, Class<?>> getTypeMap() throws SQLException { return delegate.getTypeMap(); }
        @Override public void setTypeMap(java.util.Map<String, Class<?>> map) throws SQLException { delegate.setTypeMap(map); }
        @Override public void setHoldability(int holdability) throws SQLException { delegate.setHoldability(holdability); }
        @Override public int getHoldability() throws SQLException { return delegate.getHoldability(); }
        @Override public Savepoint setSavepoint() throws SQLException { return delegate.setSavepoint(); }
        @Override public Savepoint setSavepoint(String name) throws SQLException { return delegate.setSavepoint(name); }
        @Override public void rollback(Savepoint savepoint) throws SQLException { delegate.rollback(savepoint); }
        @Override public void releaseSavepoint(Savepoint savepoint) throws SQLException { delegate.releaseSavepoint(savepoint); }
        @Override public Clob createClob() throws SQLException { return delegate.createClob(); }
        @Override public Blob createBlob() throws SQLException { return delegate.createBlob(); }
        @Override public NClob createNClob() throws SQLException { return delegate.createNClob(); }
        @Override public SQLXML createSQLXML() throws SQLException { return delegate.createSQLXML(); }
        @Override public boolean isValid(int timeout) throws SQLException { return delegate.isValid(timeout); }
        @Override public void setClientInfo(String name, String value) throws SQLClientInfoException { delegate.setClientInfo(name, value); }
        @Override public void setClientInfo(java.util.Properties properties) throws SQLClientInfoException { delegate.setClientInfo(properties); }
        @Override public String getClientInfo(String name) throws SQLException { return delegate.getClientInfo(name); }
        @Override public java.util.Properties getClientInfo() throws SQLException { return delegate.getClientInfo(); }
        @Override public Array createArrayOf(String typeName, Object[] elements) throws SQLException { return delegate.createArrayOf(typeName, elements); }
        @Override public Struct createStruct(String typeName, Object[] attributes) throws SQLException { return delegate.createStruct(typeName, attributes); }
        @Override public void setSchema(String schema) throws SQLException { delegate.setSchema(schema); }
        @Override public String getSchema() throws SQLException { return delegate.getSchema(); }
        @Override public void abort(java.util.concurrent.Executor executor) throws SQLException { delegate.abort(executor); }
        @Override public void setNetworkTimeout(java.util.concurrent.Executor executor, int milliseconds) throws SQLException { delegate.setNetworkTimeout(executor, milliseconds); }
        @Override public int getNetworkTimeout() throws SQLException { return delegate.getNetworkTimeout(); }
        @Override public <T> T unwrap(Class<T> iface) throws SQLException { return delegate.unwrap(iface); }
        @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return delegate.isWrapperFor(iface); }
    }

    /**
     * PreparedStatement wrapper that times {@code execute}, {@code executeQuery},
     * and {@code executeUpdate} calls.
     */
    private class TracingPreparedStatementProxy extends PreparedStatementWrapper {

        private final String sql;

        TracingPreparedStatementProxy(PreparedStatement delegate, String sql) {
            super(delegate);
            this.sql = sql;
        }

        @Override
        public boolean execute() throws SQLException {
            return timed(new SqlCallable<Boolean>() {
                @Override public Boolean call() throws SQLException { return TracingPreparedStatementProxy.super.execute(); }
            });
        }

        @Override
        public ResultSet executeQuery() throws SQLException {
            return timed(new SqlCallable<ResultSet>() {
                @Override public ResultSet call() throws SQLException { return TracingPreparedStatementProxy.super.executeQuery(); }
            });
        }

        @Override
        public int executeUpdate() throws SQLException {
            return timed(new SqlCallable<Integer>() {
                @Override public Integer call() throws SQLException { return TracingPreparedStatementProxy.super.executeUpdate(); }
            });
        }

        private <T> T timed(SqlCallable<T> callable) throws SQLException {
            long start = System.nanoTime();
            try {
                return callable.call();
            } finally {
                long durationMs = (System.nanoTime() - start) / 1_000_000;
                String truncatedSql = truncate(sql);
                if (durationMs > props.getSlowQueryThresholdMs()) {
                    log.warn("[SigNoz] SLOW QUERY ({}ms > {}ms): {}", durationMs, props.getSlowQueryThresholdMs(), truncatedSql);
                } else if (props.isLogAllQueries()) {
                    log.info("[SigNoz] Query ({}ms): {}", durationMs, truncatedSql);
                }
            }
        }

        private String truncate(String s) {
            if (s == null) return "";
            return s.length() > props.getMaxQueryLength() ? s.substring(0, props.getMaxQueryLength()) + "..." : s;
        }
    }

    private interface SqlCallable<T> {
        T call() throws SQLException;
    }

    /**
     * Base wrapper that delegates all PreparedStatement methods.
     * Subclasses override only the methods they want to intercept.
     */
    private static class PreparedStatementWrapper implements PreparedStatement {
        protected final PreparedStatement delegate;
        PreparedStatementWrapper(PreparedStatement delegate) { this.delegate = delegate; }

        @Override public ResultSet executeQuery() throws SQLException { return delegate.executeQuery(); }
        @Override public int executeUpdate() throws SQLException { return delegate.executeUpdate(); }
        @Override public boolean execute() throws SQLException { return delegate.execute(); }
        @Override public void setNull(int i, int t) throws SQLException { delegate.setNull(i, t); }
        @Override public void setBoolean(int i, boolean x) throws SQLException { delegate.setBoolean(i, x); }
        @Override public void setByte(int i, byte x) throws SQLException { delegate.setByte(i, x); }
        @Override public void setShort(int i, short x) throws SQLException { delegate.setShort(i, x); }
        @Override public void setInt(int i, int x) throws SQLException { delegate.setInt(i, x); }
        @Override public void setLong(int i, long x) throws SQLException { delegate.setLong(i, x); }
        @Override public void setFloat(int i, float x) throws SQLException { delegate.setFloat(i, x); }
        @Override public void setDouble(int i, double x) throws SQLException { delegate.setDouble(i, x); }
        @Override public void setBigDecimal(int i, java.math.BigDecimal x) throws SQLException { delegate.setBigDecimal(i, x); }
        @Override public void setString(int i, String x) throws SQLException { delegate.setString(i, x); }
        @Override public void setBytes(int i, byte[] x) throws SQLException { delegate.setBytes(i, x); }
        @Override public void setDate(int i, Date x) throws SQLException { delegate.setDate(i, x); }
        @Override public void setTime(int i, Time x) throws SQLException { delegate.setTime(i, x); }
        @Override public void setTimestamp(int i, Timestamp x) throws SQLException { delegate.setTimestamp(i, x); }
        @Override public void setAsciiStream(int i, java.io.InputStream x, int l) throws SQLException { delegate.setAsciiStream(i, x, l); }
        @Override @Deprecated public void setUnicodeStream(int i, java.io.InputStream x, int l) throws SQLException { delegate.setUnicodeStream(i, x, l); }
        @Override public void setBinaryStream(int i, java.io.InputStream x, int l) throws SQLException { delegate.setBinaryStream(i, x, l); }
        @Override public void clearParameters() throws SQLException { delegate.clearParameters(); }
        @Override public void setObject(int i, Object x, int t) throws SQLException { delegate.setObject(i, x, t); }
        @Override public void setObject(int i, Object x) throws SQLException { delegate.setObject(i, x); }
        @Override public void addBatch() throws SQLException { delegate.addBatch(); }
        @Override public void setRef(int i, Ref x) throws SQLException { delegate.setRef(i, x); }
        @Override public void setBlob(int i, Blob x) throws SQLException { delegate.setBlob(i, x); }
        @Override public void setClob(int i, Clob x) throws SQLException { delegate.setClob(i, x); }
        @Override public void setArray(int i, Array x) throws SQLException { delegate.setArray(i, x); }
        @Override public ResultSetMetaData getMetaData() throws SQLException { return delegate.getMetaData(); }
        @Override public void setDate(int i, Date x, java.util.Calendar c) throws SQLException { delegate.setDate(i, x, c); }
        @Override public void setTime(int i, Time x, java.util.Calendar c) throws SQLException { delegate.setTime(i, x, c); }
        @Override public void setTimestamp(int i, Timestamp x, java.util.Calendar c) throws SQLException { delegate.setTimestamp(i, x, c); }
        @Override public void setNull(int i, int t, String n) throws SQLException { delegate.setNull(i, t, n); }
        @Override public void setURL(int i, java.net.URL x) throws SQLException { delegate.setURL(i, x); }
        @Override public ParameterMetaData getParameterMetaData() throws SQLException { return delegate.getParameterMetaData(); }
        @Override public void setRowId(int i, RowId x) throws SQLException { delegate.setRowId(i, x); }
        @Override public void setNString(int i, String x) throws SQLException { delegate.setNString(i, x); }
        @Override public void setNClob(int i, NClob x) throws SQLException { delegate.setNClob(i, x); }
        @Override public void setClob(int i, java.io.Reader r, long l) throws SQLException { delegate.setClob(i, r, l); }
        @Override public void setBlob(int i, java.io.InputStream s, long l) throws SQLException { delegate.setBlob(i, s, l); }
        @Override public void setNClob(int i, java.io.Reader r, long l) throws SQLException { delegate.setNClob(i, r, l); }
        @Override public void setSQLXML(int i, SQLXML x) throws SQLException { delegate.setSQLXML(i, x); }
        @Override public void setObject(int i, Object x, int t, int s) throws SQLException { delegate.setObject(i, x, t, s); }
        @Override public void setAsciiStream(int i, java.io.InputStream x, long l) throws SQLException { delegate.setAsciiStream(i, x, l); }
        @Override public void setBinaryStream(int i, java.io.InputStream x, long l) throws SQLException { delegate.setBinaryStream(i, x, l); }
        @Override public void setCharacterStream(int i, java.io.Reader r, long l) throws SQLException { delegate.setCharacterStream(i, r, l); }
        @Override public void setAsciiStream(int i, java.io.InputStream x) throws SQLException { delegate.setAsciiStream(i, x); }
        @Override public void setBinaryStream(int i, java.io.InputStream x) throws SQLException { delegate.setBinaryStream(i, x); }
        @Override public void setCharacterStream(int i, java.io.Reader r) throws SQLException { delegate.setCharacterStream(i, r); }
        @Override public void setNCharacterStream(int i, java.io.Reader r) throws SQLException { delegate.setNCharacterStream(i, r); }
        @Override public void setClob(int i, java.io.Reader r) throws SQLException { delegate.setClob(i, r); }
        @Override public void setBlob(int i, java.io.InputStream s) throws SQLException { delegate.setBlob(i, s); }
        @Override public void setNClob(int i, java.io.Reader r) throws SQLException { delegate.setNClob(i, r); }
        @Override public void setCharacterStream(int i, java.io.Reader r, int l) throws SQLException { delegate.setCharacterStream(i, r, l); }
        @Override public void setNCharacterStream(int i, java.io.Reader r, long l) throws SQLException { delegate.setNCharacterStream(i, r, l); }

        // Statement methods
        @Override public ResultSet executeQuery(String sql) throws SQLException { return delegate.executeQuery(sql); }
        @Override public int executeUpdate(String sql) throws SQLException { return delegate.executeUpdate(sql); }
        @Override public void close() throws SQLException { delegate.close(); }
        @Override public int getMaxFieldSize() throws SQLException { return delegate.getMaxFieldSize(); }
        @Override public void setMaxFieldSize(int max) throws SQLException { delegate.setMaxFieldSize(max); }
        @Override public int getMaxRows() throws SQLException { return delegate.getMaxRows(); }
        @Override public void setMaxRows(int max) throws SQLException { delegate.setMaxRows(max); }
        @Override public void setEscapeProcessing(boolean enable) throws SQLException { delegate.setEscapeProcessing(enable); }
        @Override public int getQueryTimeout() throws SQLException { return delegate.getQueryTimeout(); }
        @Override public void setQueryTimeout(int seconds) throws SQLException { delegate.setQueryTimeout(seconds); }
        @Override public void cancel() throws SQLException { delegate.cancel(); }
        @Override public SQLWarning getWarnings() throws SQLException { return delegate.getWarnings(); }
        @Override public void clearWarnings() throws SQLException { delegate.clearWarnings(); }
        @Override public void setCursorName(String name) throws SQLException { delegate.setCursorName(name); }
        @Override public boolean execute(String sql) throws SQLException { return delegate.execute(sql); }
        @Override public ResultSet getResultSet() throws SQLException { return delegate.getResultSet(); }
        @Override public int getUpdateCount() throws SQLException { return delegate.getUpdateCount(); }
        @Override public boolean getMoreResults() throws SQLException { return delegate.getMoreResults(); }
        @Override public void setFetchDirection(int d) throws SQLException { delegate.setFetchDirection(d); }
        @Override public int getFetchDirection() throws SQLException { return delegate.getFetchDirection(); }
        @Override public void setFetchSize(int rows) throws SQLException { delegate.setFetchSize(rows); }
        @Override public int getFetchSize() throws SQLException { return delegate.getFetchSize(); }
        @Override public int getResultSetConcurrency() throws SQLException { return delegate.getResultSetConcurrency(); }
        @Override public int getResultSetType() throws SQLException { return delegate.getResultSetType(); }
        @Override public void addBatch(String sql) throws SQLException { delegate.addBatch(sql); }
        @Override public void clearBatch() throws SQLException { delegate.clearBatch(); }
        @Override public int[] executeBatch() throws SQLException { return delegate.executeBatch(); }
        @Override public Connection getConnection() throws SQLException { return delegate.getConnection(); }
        @Override public boolean getMoreResults(int current) throws SQLException { return delegate.getMoreResults(current); }
        @Override public ResultSet getGeneratedKeys() throws SQLException { return delegate.getGeneratedKeys(); }
        @Override public int executeUpdate(String sql, int a) throws SQLException { return delegate.executeUpdate(sql, a); }
        @Override public int executeUpdate(String sql, int[] c) throws SQLException { return delegate.executeUpdate(sql, c); }
        @Override public int executeUpdate(String sql, String[] c) throws SQLException { return delegate.executeUpdate(sql, c); }
        @Override public boolean execute(String sql, int a) throws SQLException { return delegate.execute(sql, a); }
        @Override public boolean execute(String sql, int[] c) throws SQLException { return delegate.execute(sql, c); }
        @Override public boolean execute(String sql, String[] c) throws SQLException { return delegate.execute(sql, c); }
        @Override public int getResultSetHoldability() throws SQLException { return delegate.getResultSetHoldability(); }
        @Override public boolean isClosed() throws SQLException { return delegate.isClosed(); }
        @Override public void setPoolable(boolean poolable) throws SQLException { delegate.setPoolable(poolable); }
        @Override public boolean isPoolable() throws SQLException { return delegate.isPoolable(); }
        @Override public void closeOnCompletion() throws SQLException { delegate.closeOnCompletion(); }
        @Override public boolean isCloseOnCompletion() throws SQLException { return delegate.isCloseOnCompletion(); }
        @Override public <T> T unwrap(Class<T> iface) throws SQLException { return delegate.unwrap(iface); }
        @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return delegate.isWrapperFor(iface); }
    }
}
